# Generated by Django 4.2.19 on 2025-02-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_complaint_id_alter_flat_has_balcony_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_pure_phone',
        ),
    ]
