# Generated by Django 4.2.19 on 2025-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_rename_owners_phonenumber_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
