# Generated by Django 4.2.19 on 2025-02-27 19:43

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.owners_phonenumber:
            continue

        try:
            parsed = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(parsed):
                flat.owner_pure_phone = phonenumbers.format_number(...)
                flat.save(update_fields=['owner_pure_phone'])
        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = None
            flat.save()

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_flat_owners_phonenumber'),  # Укажите актуальную
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers),
    ]