# Generated by Django 4.2.19 on 2025-02-27 19:43

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    batch_size = 500
    flats = []

    for flat in Flat.objects.iterator(chunk_size=2000):
        flat.owner_pure_phone = None  # Значение по умолчанию
        if flat.owners_phonenumber:  # Проверяем, не пустой ли номер
            try:
                parsed = phonenumbers.parse(flat.owners_phonenumber, 'RU')
                if phonenumbers.is_valid_number(parsed):
                    flat.owner_pure_phone = phonenumbers.format_number(
                        parsed,
                        phonenumbers.PhoneNumberFormat.E164
                    )
            except phonenumbers.NumberParseException:
                pass  # Значение уже None

        flats.append(flat)

        if len(flats) >= batch_size:
            Flat.objects.bulk_update(flats, ['owner_pure_phone'])
            flats = []


    if flats:
        Flat.objects.bulk_update(flats, ['owner_pure_phone'])


class Migration(migrations.Migration):
    dependencies = [('property', '0009_flat_owners_phonenumber')]
    operations = [migrations.RunPython(normalize_phonenumbers)]
