# Generated by Django 4.2.19 on 2025-03-01 18:05

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone
            }
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]






