# Generated by Django 4.2.19 on 2025-03-04 11:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owners_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='RU', verbose_name='Номер владельца'),
        ),
    ]
